allowBuilds:
    msw: false

catalog:
    vite: npm:@voidzero-dev/vite-plus-core@0.2.9
    vite-plus: 1.0.0-rc.0

minimumReleaseAgeExclude:
    - "@types/node@24.19.0"

overrides:
    vite: "catalog:"

peerDependencyRules:
    allowAny:
        - vite
    allowedVersions:
        vite: "*"